name: Create Release for SalesforcePR

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the main branch

env:
  ASSET_NAME: salesforce-package

jobs:
  create-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, test, prod]  # Build for all environments

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Configuration File
        run: |
          CONFIG_FILE="configs/${{ matrix.environment }}.yaml"
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "Error: Configuration file $CONFIG_FILE not found!"
            exit 1
          fi
          echo "Found configuration file: $CONFIG_FILE"

      - name: Load Configuration
        id: config
        run: |
          echo "Loading configuration for ${{ matrix.environment }}..."
          API_URL=$(yq eval '.apiUrl' configs/${{ matrix.environment }}.yaml)
          API_KEY=$(yq eval '.apiKey' configs/${{ matrix.environment }}.yaml)
          echo "API_URL=${API_URL}" >> $GITHUB_ENV
          echo "API_KEY=${API_KEY}" >> $GITHUB_ENV

      - name: Prepare Files for Archive
        run: |
          echo "Preparing files for environment: ${{ matrix.environment }}..."
          mkdir -p archive
          cp configs/${{ matrix.environment }}.yaml archive/config.yaml
          cp -r src archive/  # Include source code
          
          # Add metadata to a README file
          echo "Environment: ${{ matrix.environment }}" > archive/README.txt
          echo "API URL: ${API_URL}" >> archive/README.txt
          echo "API Key: ${API_KEY}" >> archive/README.txt

          # Create ZIP archive
          zip -r ${{ env.ASSET_NAME }}-${{ matrix.environment }}.zip ./archive
          ls -lh ${{ env.ASSET_NAME }}-${{ matrix.environment }}.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}-${{ matrix.environment }}
          release_name: Release v1.0.${{ github.run_number }} (${{ matrix.environment }})
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ASSET_NAME }}-${{ matrix.environment }}.zip
          asset_name: ${{ env.ASSET_NAME }}-${{ matrix.environment }}.zip
          asset_content_type: application/zip
