name: Manual Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment (dev, test, prod)'
        required: true
        default: 'dev'

env:
  ASSET_NAME: salesforce-package

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Release Asset
        uses: dsaltares/fetch-gh-release-asset@v1
        with:
          repo: ${{ github.repository }}
          version: latest
          file: ${{ env.ASSET_NAME }}-${{ github.event.inputs.environment }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Release Files
        run: |
          mkdir -p deployment
          unzip ${{ env.ASSET_NAME }}-${{ github.event.inputs.environment }}.zip -d deployment
          ls -la deployment

      - name: Deploy to ${{ github.event.inputs.environment }}
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }} environment..."
          cat deployment/config.yaml
          echo "Deployment successful for ${{ github.event.inputs.environment }}!"
